// Code generated by cmd/gencatalog; DO NOT EDIT.
// Source: https://servicereference.us-east-1.amazonaws.com/v1/ssm/ssm.json
// Retrieved: 2026-07-20T08:15:00Z
// Schema: AWS Service Reference v1.4
// SHA-256: 70b7fffa355168623052e1dfa6b419cc20e262fd981c58fbefca3f9dd1a716e7

package aws

// WO-64@v3: expose the pinned evidence digest to catalog consumers.
const resourceApplicabilityCatalogDigest = "70b7fffa355168623052e1dfa6b419cc20e262fd981c58fbefca3f9dd1a716e7"

// WO-64@v3: resourceApplicabilityCatalog is pinned generated evidence, not runtime inference.
var resourceApplicabilityCatalog = map[string]ResourceApplicability{
	"ssm:AddTagsToResource":   ResourceApplicabilitySupported,
	"ssm:DescribeActivations": ResourceApplicabilityNone,
	"ssm:GetDocument":         ResourceApplicabilitySupported,
}

// WO-64@v3: ResourceApplicability reports only what the AWS JSON schema proves.
type ResourceApplicability string

const (
	ResourceApplicabilitySupported ResourceApplicability = "supported"
	ResourceApplicabilityNone      ResourceApplicability = "none"
)
